# Introdução
<div style="text-align: justify"> 

Material inteiramente baseado em Albert R Meyer et al. Mathematics for computer science. Chapter, 13:253–272, 2002. Disponível em https://courses.csail.mit.edu/6.042/spring18/mcs.pdf

</div>

## Proposições

<div style="text-align: justify"> 

::: {#def-line}

## Proposição

Uma proposição é uma afirmação (comunicação) que ou é verdadeira ou falsa.

Por exemplo, as duas afirmações a seguir são proposições. A primeira é verdadeira enquanto a segunda é falsa.
:::

::: {#prp-line1}

$2 + 3 = 5$
:::

::: {#prp-line2}

$1 + 1 = 3$
:::

Ser falso ou verdadeiro parece não limitar muito nossas possibilidades, mas exclui alguns casos com o "Es tu Romeo?" e "Me dê um SS!". Também exclui afirmações em que a verdade varia de acordo com as circunstâncias como, "São 17 horas" ou "as ações vão subir amanhã".

Infelizmente, nem sempre é trivial decidir se uma dada proposição é verdadeira ou falsa:


::: {#exm-line1}

## Afirmação

*Para todo inteiro não-negativo $n$ o valor de $n^2 + n + 41$ é um número primo*

$$
P(n) = primo
$$
:::

Um número primo é um inteiro maior que 1 que não é divisível por nenhum outro número inteiro maior que 1, a não ser ele mesmo. Por exemplo, 2, 3, 5, 7, 11 são os primeiros cinco números primos. Vamos tentar uma experimentação numérica para verifcar essa proposição. Considere:

$$
p(n) ::= n^2 + n + 41
$$

Começamos com $p(0) = 41$, que é primo. Então,

$$
p(1) = 43, p(2) = 47, p(3) = 53, \cdots , p(20) = 461
$$

são todos primos. Podemos seguir validando a proposição até $n = 39$ e confirmar que $p(39) = 1601$ é primo. Porém, $p(40) = 41 \times 41$, que não é primo. Portanto a proposição é falsa, uma vez que não é verdadeiro que $p(n)$ seja primo para *todos* os inteiros não-negativos $n$. Esse exemplo evidencia um ponto importante que, em geral, não é possível validar uma afirmação sobre um conjunto infinito checando uma amostra finita de seus elementos, não importa o quão grande sera a amostra.

Tais proposições a respeito de *todos* ou *qualquer* número ou itens de algum tipo são bastante comuns e possuem uma notação especial. Com essa notação, a proposição acima seria:

::: {#exm-line2}

## Proposição

$\quad \forall \quad n \in \mathbb{N}, \quad p(n)$ é primo
:::

Em que o símbolo $\forall$ significa \textit{para todo}, o símbolo $\mathbb{N}$ representa o conjunto de inteiros não-negativos e $\in$ significa "pertence".

</div>


## Predicados

<div style="text-align: justify"> 

Um predicado pode ser entendido como uma proposição cuja verdade depende do valor de uma ou mais variáveis. Portanto, “n é um quadrado perfeito” descreve um predicado, uma vez que você não pode dizer se é verdadeiro ou falso até saber qual é o valor da variável n. Uma vez que você sabe, por exemplo, que n é igual a 4, o predicado se torna a proposição verdadeira “4 é um quadrado perfeito”.

Lembre-se, nada diz que a proposição precisa ser verdadeira: se o valor de n fosse 5, você teria a proposição falsa “5 é um quadrado perfeito.” Assim como outras proposições, os predicados geralmente são nomeados com uma letra. Além disso, uma notação semelhante à de uma função é usada para denotar um predicado fornecido com valores variáveis específicos. Por exemplo, podemos usar o nome “P” para o predicado abaixo.

$$
P(n) ::= \textrm{``} n \textrm{ é um quadrado perfeito",}
$$

e repita as observações acima afirmando que P(4) é verdadeiro, e P(5) é falso.
Essa notação para predicados é confusamente similar à notação de funções ordinárias.
Se P é um predicado, então P(n) é verdadeiro ou falso, dependendo do valor de n.
Por outro lado, se p é uma função ordinária, como $n^2 +1$, então p(n) é uma quantidade numérica. Não confunda esses dois!

</div>

## Método Axiomático
<div style="text-align: justify"> 
O procedimento padrão para estabelecer a verdade na matemática foi inventado por Euclides, um matemático que trabalhava em Alexandria, Egito, por volta de 300 a.C. Sua ideia era começar com cinco suposições sobre geometria, que pareciam inegáveis com base na experiência direta. (Por exemplo, "Existe um segmento de linha reta entre cada par de pontos".) Proposições como essas, que são simplesmente aceitas como verdadeiras, são chamadas de axiomas.

A partir desses axiomas, Euclides estabeleceu a verdade de muitas outras proposições fornecendo "provas". Uma prova é uma sequência de deduções lógicas a partir de axiomas e declarações previamente provadas que conclui com a proposição em questão.

Existem vários termos comuns para uma proposição que foi provada. Os diferentes termos sugerem o papel da proposição dentro de um corpo de trabalho maior.

- Proposições verdadeiras importantes são chamadas de _teoremas_.
- Um _lema_ é uma proposição preliminar útil para provar proposições posteriores.
- Um _corolário_ é uma proposição que segue em apenas alguns passos lógicos de um teorema.

Essas definições não são precisas. Na verdade, às vezes um bom lema acaba se tornando muito mais importante do que o teorema que ele originalmente pretendia provar.

A abordagem de axiomas e provas de Euclides, agora chamada de método axiomático, continua sendo a base da matemática até hoje. De fato, apenas um pequeno conjunto de axiomas, chamados axiomas de Zermelo-Fraenkel com a escolha (ZFC), junto com algumas regras de dedução lógica, parecem ser suficientes para derivar essencialmente toda a matemática.
</div>

### Deduções Lógicas
<div style="text-align: justify"> 
Deduções lógicas, ou **regras de inferência**, são usadas para provar novas proposições utilizando aquelas já previamente provadas.

Uma regra de inferência fundamental é o **modus ponens**. Essa regra diz que uma prova de \(P\) junto com uma prova de que \(P \text{ IMPLICA } Q\) é uma prova de \(Q\).

As regras de inferência são, às vezes, escritas em uma notação peculiar. Por exemplo, o **modus ponens** é escrito assim:

**Regra.**

$$
\frac{P, \, P \text{ \small{IMPLICA} } Q}{Q}
$$

Quando as declarações acima da linha, chamadas de __antecedentes__, são provadas, podemos considerar que a declaração abaixo da linha, chamada de __conclusão__ ou __consequente__, também está provada.

Um requisito fundamental de uma regra de inferência é que ela deve ser **sólida**: uma atribuição de valores de verdade às letras  $(P), (Q), . . .$  que torna todos os antecedentes verdadeiros deve também tornar o consequente verdadeiro. Assim, se começarmos com axiomas verdadeiros e aplicarmos regras de inferência sólidas, tudo o que provamos também será verdadeiro.

Existem muitas outras regras de inferência naturais e sólidas, por exemplo:

**Regra.**

$$
\frac{P \text{ \small{IMPLICA} } Q, \, Q \text{ \small{IMPLICA} } R}{P \text{ \small{IMPLICA} } R}
$$

**Regra.**

$$
\frac{\text{\small{NÃO}} (P) \text{ \small{IMPLICA} } \text{\small{NÃO}} (Q)}{Q \text{ \small{IMPLICA} } P}
$$

Por outro lado,

**Não-Regra.**

$$
\frac{\text{\small{NÃO}} (P) \text{ \small{IMPLICA} } \text{\small{NÃO}} (Q)}{P \text{ \small{IMPLICA} } Q}
$$

não é sólida: se $(P)$ for atribuído como verdadeiro \(T\) e $(Q)$ como falso \(F\), então o antecedente é verdadeiro e o consequente não é.

Assim como com axiomas, não seremos muito formais sobre o conjunto de regras de inferência legais. Cada passo em uma prova deve ser claro e "lógico"; em particular, você deve indicar quais fatos previamente provados são usados para derivar cada nova conclusão.
</div>

### Padrões de Prova
<div style="text-align: justify"> 
Em princípio, uma prova pode ser qualquer sequência de deduções lógicas a partir de axiomas e declarações previamente provadas que conclui com a proposição em questão. Essa liberdade na construção de uma prova pode parecer avassaladora no início. Como você começa uma prova?

Aqui está a boa notícia: muitas provas seguem um, de um alguns templates padrão. Cada prova tem seus próprios detalhes, é claro, mas esses templates pelo menos fornecem um esboço para você preencher. Vamos passar por vários desses padrões, apontando a ideia básica, os erros comuns e dando alguns exemplos. Muitos desses templates se encaixam; um pode lhe dar um esboço de alto nível, enquanto outros ajudam em um nível maior de detalhe.

As receitas abaixo são muito específicas às vezes, dizendo exatamente quais palavras escrever em seu papel. Você certamente é livre para expressar as coisas do seu jeito; estamos apenas lhe dando algo que você poderia dizer para que nunca fique completamente perdido.
</div>

## Provando uma Implicação
<div style="text-align: justify"> 
Proposições da forma "Se $(P)$, então $(Q)$" são chamadas de **implicações**. Essa implicação é frequentemente reformulada como "$(P \text{ \small{IMPLICA} } Q)$."

Aqui estão alguns exemplos:

- (Fórmula Quadrática) Se $ax^2 + bx + c = 0$ e $a \neq 0$, então

$$
x = \left(-b \pm \sqrt{b^2 - 4ac}\right) / 2a.
$$

- (Conjectura de Goldbach reformulada) Se $(n)$ é um número inteiro par maior que 2, então $(n)$ é a soma de dois números primos.

- Se $(0 \leq x \leq 2)$, então $(-x^3 + 4x + 1 > 0)$.

Existem alguns métodos padrão para provar uma implicação.
</div>

### Método #1
<div style="text-align: justify"> 

Para provar que $(P \text{ \small{IMPLICA} } Q)$:

1. Escreva: "Assuma $(P)$."
2. Mostre que $(Q)$ segue logicamente.

**Exemplo**

::: {#thm-1}
Se $\quad (0 \leq x \leq 2),\quad$ então $\quad (-x^3 + 4x + 1 > 0)$
:::

Antes de escrevermos uma prova deste teorema, temos que fazer alguns rascunhos para entender por que ele é verdadeiro.

A desigualdade certamente é válida para $(x = 0)$ então o lado esquerdo é igual a 1, e 1 > 0. À medida que $(x)$ cresce, o termo $(4x)$ (que é positivo) inicialmente parece ter maior magnitude do que $(x^3)$ (que é negativo). Por exemplo, quando $(x = 1)$ temos $(4x = 4)$ mas $(x^3 = -1)$ Na verdade, parece que $(x^3)$ não começa a dominar até $(x > 2)$ Portanto, parece que a parte $(x^3 + 4x)$ deve ser não negativa para todo $(x)$ entre 0 e 2, o que implicaria que $(x^3 + 4x + 1)$ é positivo.

Até agora, tudo bem. Mas ainda precisamos substituir todas essas expressões como "parece que" por argumentos sólidos e lógicos. Podemos obter uma melhor compreensão da parte crítica $(x^3 + 4x)$ ao fatorá-la, o que não é muito difícil:

$$
-x^3 + 4x = x(2 - x)(2 + x)
$$

Aha! Para $(x)$ entre 0 e 2, todos os termos no lado direito são não negativos. E o produto de termos não negativos também é não negativo. Vamos organizar essa avalanche de observações em uma prova limpa.

**Prova.** Assuma $(0 \leq x \leq 2)$. Então $(x)$, $(2 - x)$ e $(2 + x)$ são todos não negativos. Portanto, o produto desses termos também é não negativo. Adicionando 1 a esse produto obtemos um número positivo, assim:
</div>

$$
x(2 - x)(2 + x) + 1 > 0
$$

Multiplicando no lado esquerdo prova que

$$
-x^3 + 4x + 1 > 0
$$

como afirmado. $\hspace{330pt} \blacksquare$


<div style="text-align: justify">
Existem alguns pontos aqui que se aplicam a todas as provas:

- Você frequentemente precisará fazer alguns rascunhos enquanto tenta descobrir os passos lógicos de uma prova. Seus rascunhos podem ser tão desorganizados quanto você quiser — cheios de becos sem saída, diagramas estranhos, palavras obscenas, seja o que for. Mas mantenha seus rascunhos separados da sua prova final, que deve ser clara e concisa.

- As provas normalmente começam com a palavra "Prova" e terminam com algum tipo de delimitador como $\blacksquare$ ou "QED." O único propósito dessas convenções é esclarecer onde as provas começam e terminam.
</div>

### Método #2

<div style="text-align: justify">
Uma implicação “$P \text{ \small{IMPLICA} } Q$” é logicamente equivalente à sua contrapositiva $\text{\small{NÃO}}(Q) \text{ \small{IMPLICA} } \text{\small{NÃO}}(P)$:  
Provar uma é tão bom quanto provar a outra, e às vezes provar a contrapositiva é mais fácil do que provar a declaração original. Se for o caso, você pode proceder da seguinte forma:

1. Escreva: “Vamos provar a contrapositiva:” e, em seguida, declare a contrapositiva.
2. Prossiga como no Método #1.

**Exemplo**  
**Teorema** Se $r$ é irracional, então $\sqrt{r}$ é irracional.

Um número é racional quando é igual a uma fração de inteiros — ou seja, se é igual a $m/n$ para alguns inteiros $m$ e $n$. Se não for racional, então é chamado de irracional. Portanto, devemos mostrar que se $r$$ não é uma razão de inteiros, então $\sqrt{r}$ também não é uma razão de inteiros. Isso é bem complicado! Podemos eliminar ambas as negações e simplificar a prova usando a contrapositiva em vez disso.

**Prova.** Vamos provar a contrapositiva: se $\sqrt{r}$ é racional, então $r$ é racional.  
Assuma que $\sqrt{r}$ é racional. Então, existem inteiros $m$ e $n$ tais que:

$$
\sqrt{r} = \frac{m}{n}
$$

Elevando os dois lados ao quadrado, temos:

$$
r = \frac{m^2}{n^2}
$$

Como $m^2$ e $n^2$ são inteiros, $r$ é racional.
</div>

## Provando "se somente se ""
Muitos teoremas matemáticos afirmam que duas declarações são logicamente equivalentes; ou seja, uma é válida se, e somente se, a outra também for. Aqui está um exemplo que é conhecido há milhares de anos:
Dois triângulos têm os mesmos comprimentos de lados se, e somente se, dois comprimentos de lados e o ângulo entre esses lados forem os mesmos.
A expressão "se, e somente se" aparece com tanta frequência que muitas vezes é abreviada como "sse".

### Método #1: Prove que Cada Declaração Implica na Outra
A declaração "P SSE Q" é equivalente a duas declarações: "P IMPLICA Q" e "Q IMPLICA P". Então, você pode provar um "sse" provando duas implicações:

1. Escreva: "Provamos que P implica Q e vice-versa."
2. Escreva: "Primeiro, mostramos que P implica Q." Faça isso por um dos métodos da Seção 1.5.
3. Escreva: "Agora, mostramos que Q implica P." Novamente, faça isso por um dos métodos da Seção 1.5.

### Método #2: Construa uma Cadeia de SSE
Para provar que P é verdadeiro se, e somente se, Q for verdadeiro:

1. Escreva: "Construímos uma cadeia de implicações se, e somente se."
2. Prove que P é equivalente a uma segunda declaração, que é equivalente a uma terceira, e assim por diante, até que você chegue a Q.

Esse método às vezes requer mais criatividade do que o primeiro, mas o resultado pode ser uma prova curta e elegante.

### Exemplo
A **desvio padrão** de uma sequência de valores $x_1, x_2, \dots, x_n$ é definida como:

$$
s = \sqrt{\frac{(x_1 - \mu)^2 + (x_2 - \mu)^2 + \dots + (x_n - \mu)^2}{n}}
$$

onde $\mu$ é a média dos valores:

$$
\mu = \frac{x_1 + x_2 + \dots + x_n}{n}
$$

**Teorema 1.6.1.** O desvio padrão de uma sequência de valores $x_1, x_2, \dots, x_n$ é zero se, e somente se, todos os valores forem iguais à média.
Por exemplo, o desvio padrão das notas de teste é zero se, e somente se, todos tiverem exatamente a média da turma.

**Prova.** Construímos uma cadeia de implicações "sse", começando com a declaração de que o desvio padrão é zero:

$$
s = \sqrt{\frac{(x_1 - \mu)^2 + (x_2 - \mu)^2 + \dots + (x_n - \mu)^2}{n}} = 0
$$

## Modus ponens

Uma vez que provamos uma implicação

$$
P \implies Q
$$

como sendo sempre verdadeira, queremos usá-la. Logo provaremos que a implicação

> Se $n$ é par, então $n^2$ é par.

é sempre verdadeira. Sabemos que não pode ser falsa, então vamos escrever as 3 linhas relevantes de sua tabela verdade e suprimir a linha correspondente à implicação ser falsa:

| $P$ | $Q$ | $P \implies Q$ |
|:----:|:----:|:--------------:|
|  T   |  T   |       T        |
|  F   |  T   |       T        |
|  F   |  F   |       T        |

Note que, se pegarmos um número como $n = 14$, sabemos que ele é par e, portanto, a hipótese é verdadeira. Pela tabela verdade, sabemos que a conclusão também deve ser verdadeira — o número $n^2 = 14^2$ é par. Não precisamos fazer mais nada; a tabela verdade, e nossa prova, garantem que a conclusão é verdadeira.

De modo mais geral, se provamos que

$$
P \implies Q
$$

é sempre verdadeiro, então, se sabemos que a hipótese $P$ é verdadeira, a conclusão $Q$ também deve ser verdadeira.

::: {#def-modusponens}

### Modus ponens

A dedução:

- $P$ implica $Q$ é verdadeiro, e
- $P$ é verdadeiro
- logo, $Q$ deve ser verdadeiro.

é chamada de **modus ponens**.
:::

Esta dedução lógica foi formalizada pela primeira vez por Teofrasto.

Note que, se tivermos provado a implicação $P \implies Q$ como verdadeira, mas a hipótese $P$ for falsa, então **não podemos** concluir nada sobre o valor de verdade da conclusão. Quando a hipótese é falsa, o valor de verdade da conclusão não importa — a implicação ainda é verdadeira. Podemos verificar isso considerando as duas linhas relevantes da tabela verdade da implicação.

| $P$ | $Q$ | $P \implies Q$ |
|:----:|:----:|:--------------:|
|  F   |  T   |       T        |
|  F   |  F   |       T        |

De forma similar, se tivermos provado a implicação $P \implies Q$ como verdadeira, e tivermos provado que a conclusão $Q$ é verdadeira, então não podemos concluir nada sobre o valor de verdade da hipótese $P$. Novamente, isso é facilmente verificado considerando as duas linhas relevantes da tabela verdade da implicação.

| $P$ | $Q$ | $P \implies Q$ |
|:----:|:----:|:--------------:|
|  T   |  T   |       T        |
|  F   |  T   |       T        |

No entanto, há uma outra instância na qual podemos fazer uma conclusão válida. Considere novamente a tabela verdade quando a implicação $P \implies Q$ é verdadeira, mas a conclusão $Q$ é falsa:

| $P$ | $Q$ | $P \implies Q$ |
|:----:|:----:|:--------------:|
|  F   |  F   |       T        |

Aqui, a única possibilidade é que a hipótese deve ser falsa. Isso nos permite fazer outra dedução válida.

::: {#def-modustollens}

### Modus tollens

A dedução:

- $P$ implica $Q$ é verdadeira, e
- $Q$ é falso
- logo, $P$ deve ser falso.

é chamada de **modus tollens**.
:::

Então, quando sabemos (voltando ao nosso exemplo) que:

> Se ele é Shakespeare, então ele está morto.

podemos concluir que qualquer pessoa viva não é Shakespeare.

#### Afirmar o consequente e negar o antecedente

A má aplicação do **modus ponens** é uma fonte frequente de erros lógicos. Um erro muito comum é chamado de “afirmar o consequente”.

::: {#wrn-errocomum1}

### Um erro lógico comum.
A falsa dedução:

- $P$ implica $Q$ é verdadeiro, e
- $Q$ é verdadeiro,
- e, portanto, $P$ deve ser verdadeiro.

é chamada de **afirmar o consequente**.
:::

> O fluxo de lógica está errado — verifique a tabela verdade. Além disso, a notação de seta para a implicação, $\implies$, nos ajuda a lembrar que a verdade deve fluir da hipótese para a conclusão, e não o contrário.

Para ver quão errado isso pode ser, considere novamente a verdadeira implicação:

- Se ele é Shakespeare, então ele está morto.

Se afirmássemos o consequente, então qualquer homem morto deve ser Shakespeare.

Afirmar o consequente às vezes é usado como uma técnica retórica (especialmente por quem propaga bobagens):

> Se eles são Galileu, então são oprimidos. Estou sendo oprimido, logo devo ser Galileu.

ou (quando sentindo pena de si mesmo)

> Se eles são grandes artistas, então são incompreendidos. Sou incompreendido, logo devo ser um grande artista.

E a falácia da seção de comentários nas redes sociais:

> Se eu digo a verdade, ofendo as pessoas. Estou ofendendo, logo estou dizendo a verdade.
Tenha cuidado com a afirmação do consequente — ela aparece com frequência e é sempre falaciosa. Um erro lógico muito semelhante é chamado de "negar o antecedente".

::: {#wrn-errocomum2}

#### Outro erro lógico comum.

A falsa dedução:

- $P$ implica $Q$ é verdadeiro, e
- $P$ é falso,
- e, portanto, $Q$ deve ser falso.

:::

é chamada de **negar o antecedente** e é uma má aplicação do **modus tollens**.

Aqui estão alguns exemplos:

> Se eu fui a Toronto, então visitei o Canadá. Eu não fui a Toronto, então não visitei o Canadá.

> Se ele é Shakespeare então ele está morto. Abraham Linconl não é Shakespeare, então ele deve estar vivo.

> Se tem gosto ruim então deve ser saudável. Isso tem gosto bom, então não deve ser saudável.

### Encadeando implicações

Quando construímos uma prova de que $P \implies Q$ é verdadeira, não fazemos isso de uma só vez. Em vez disso, dividimos em uma sequência de implicações menores e mais fáceis, que podemos encadear. Para ver como isso funciona, considere o seguinte:

#### Resultado

Seja $P$, $Q$ e $R$ declarações. Então, a seguinte afirmação é sempre verdadeira:

$$
\Big( (P \implies R) \land (R \implies Q) \Big) \implies (P \implies Q)
$$

Este resultado é um exemplo de uma tautologia, uma afirmação que é sempre verdadeira. Voltaremos às tautologias mais tarde no texto. Para mostrar que é sempre verdadeira, poderíamos construir a tabela verdade ou usar algum raciocínio. Ambos os métodos são provas, mas não seremos tão formais até o próximo capítulo. A tabela verdade não é difícil de construir, mas um pouco tediosa; como cada uma de $P$, $Q$, $R$ pode ser verdadeira ou falsa, há $2^3 = 8$ linhas a considerar:

| $P$ | $Q$ | $R$ | $P \implies R$ | $R \implies Q$ | $P \implies Q$ | A afirmação |
|:----:|:----:|:----:|:--------------:|:--------------:|:--------------:|:------------:|
|  T   |  T   |  T   |       T        |       T        |       T        |       T      |
|  T   |  T   |  F   |       F        |       T        |       T        |       T      |
|  T   |  F   |  T   |       T        |       F        |       F        |       T      |
|  T   |  F   |  F   |       F        |       T        |       F        |       T      |
|  F   |  T   |  T   |       T        |       T        |       T        |       T      |
|  F   |  T   |  F   |       T        |       T        |       T        |       T      |
|  F   |  F   |  T   |       T        |       F        |       T        |       T      |
|  F   |  F   |  F   |       T        |       T        |       T        |       T      |

A tabela acima é uma maneira perfeitamente razoável de mostrar que a afirmação é sempre verdadeira. No entanto, podemos fazer o mesmo apenas com um pouco de raciocínio; isso também melhora nossa compreensão da afirmação. Apresentaremos o argumento em forma de pontos:

- A declaração é uma implicação com a hipótese $((P \implies R) \land (R \implies Q))$ e a conclusão $(P \implies Q)$. Uma implicação é falsa quando a hipótese é verdadeira, mas a conclusão é falsa; caso contrário, a implicação é verdadeira.

- Como a conclusão, $(P \implies Q)$, é uma implicação, só pode ser falsa quando sua hipótese é verdadeira e sua conclusão é falsa. Portanto, devemos ter que $P$ é verdadeiro, mas $Q$ é falso.

- Para que a hipótese seja verdadeira, ambas as implicações, $(P \implies R)$ e $(R \implies Q)$, devem ser verdadeiras (já que uma conjunção de duas afirmações só é verdadeira quando ambas são verdadeiras).

  - Como $P$ é verdadeiro e exigimos que $(P \implies R)$ seja verdadeiro, $R$ deve ser verdadeiro.
  
  - Como $Q$ é falso e exigimos que $(R \implies Q)$ seja verdadeiro, $R$ deve ser falso.

Mas, como $R$ é uma afirmação, ela não pode ser verdadeira e falsa ao mesmo tempo.

- Portanto, não há como fazer a afirmação ser falsa. Como nunca é falsa, ela deve ser sempre verdadeira.

Então, voltando à declaração $P \implies Q$. Gostaríamos de mostrar que é sempre verdadeira, mas não podemos fazê-lo de uma só vez. Em vez disso, assumimos que podemos dar dois passos menores e provar que as duas implicações $(P \implies R)$ e $(R \implies Q)$ são sempre verdadeiras. A conjunção das duas implicações, $(P \implies R) \land (R \implies Q)$, também é verdadeira e é exatamente a hipótese do **Resultado 2.5.5**. Como a implicação no **Resultado 2.5.5** é sempre verdadeira e sua hipótese é verdadeira — **modus ponens** — sua conclusão deve ser verdadeira.

Portanto, enquanto poderíamos tentar provar $(P \implies Q)$ de uma só vez, é suficiente provar que é verdadeira em dois passos menores $(P \implies R)$ e $(R \implies Q)$. Mais genericamente, ao provarmos $(P \implies Q)$, provaremos uma sequência de implicações:

$$
P \implies P_1 
$$

$$
P_1 \implies P_2 \
$$

$$
P_2 \implies P_3 \
$$

$$
\dots \
$$

$$
P_n \implies Q
$$

onde cada uma dessas implicações intermediárias é mais fácil de provar.

Uma vez feito isso, considere o que acontece se $P$ for verdadeiro ou falso:

> **$P$ é verdadeiro:** Se $P$ é verdadeiro, a primeira implicação nos diz que $P_1$ é verdadeiro (**modus ponens**). Então, como $P_1$ é verdadeiro, a próxima implicação nos diz que $P_2$ é verdadeiro (novamente **modus ponens**). Como $P_2$ é verdadeiro, $P_3$ é verdadeiro, $P_4$ é verdadeiro, e assim por diante, até que possamos concluir que $Q$ é verdadeiro. Como $P$ é verdadeiro e $Q$ é verdadeiro, a implicação $P \implies Q$ é verdadeira.

> **$P$ é falso:** Por outro lado, se $P$ for falso, sabemos, apenas olhando a tabela verdade da implicação, que a implicação $P \implies Q$ é verdadeira.

Note que, quando $P$ é falso, o fato de que $(P \implies Q)$ é verdadeiro é imediato e simplesmente depende da tabela verdade da implicação; não precisamos fazer nenhum trabalho ou raciocínio. Por outro lado, quando $P$ é verdadeiro, precisamos trabalhar para mostrar que $(P \implies Q)$ é verdadeira. Por essa razão, quase todas as nossas provas começarão com a suposição de que $P$ é verdadeiro. Geralmente deixamos o caso "P é falso" implícito, assumindo que nosso leitor conhece as tabelas verdade.